# Generated by Django 3.2.12 on 2022-03-11 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('avance', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fechaInicio', models.DateField()),
                ('fechaLimite', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('informacionAdicional', models.CharField(blank=True, max_length=500)),
                ('empleadosProyecto', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('usuarioCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_cliente', to=settings.AUTH_USER_MODEL)),
                ('usuarioEncargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Baja', max_length=5)),
                ('estado', models.CharField(choices=[('SIN_COMENZAR', 'Sin comenzar'), ('TRABAJANDO', 'Trabajando en ello'), ('TRABADO', 'Trabado'), ('EN_REVISION', 'En revisión'), ('TERMINADO', 'Terminado')], default='SIN_COMENZAR', max_length=25)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
                ('usuarioEmpleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado'), ('CLIENTE', 'Cliente')], max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('asistencia', models.CharField(blank=True, max_length=250)),
                ('informacionAdicional', models.CharField(blank=True, max_length=500)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
